module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    PRODUCT_OFFERS:'productOffer',
    CATEGORY_OFFERS:'categoryOffer',
    COUPON_COLLECTION:'coupon',
    WISHLIST_COLLECTION:'wishlist'
}